# Prerequisites
  -  name: Adding the EPEL Repository to Compute (CentOS)
     yum:
       name:
         -  epel-release
         -  python34
         -  python-devel
         -  gcc
       state: present

  -  name: Enabling EPEL Repository in Compute (CentOS)
     ini_file:
       dest: /etc/yum.repos.d/epel.repo
       section: epel
       option: enabled
       value: 1

  -  name: Reload Packages (CentOS)
     yum:
       name: "*"
       state: latest

# Installation of NTP
  -  name: Installation of NTP (Chrony) in Compute (CentOS)
     yum:
       name: chrony
       state: present

  -  name: Enable and Start NTP in Compute (CentOS)
     systemd:
       name: chronyd.service
       state: restarted
       enabled: true

# Installation of OpenStack Packages
  -  name: Installation of OpenStack Train Release in Compute (CentOS)
     yum:
       name: centos-release-openstack-train
       state: present

  -  name: Upgrade Packages (CentOS)
     yum:
       name: "*"
       state: latest

  -  name: Installation of OpenStack Client and SELinux Security in Compute (CentOS)
     yum:
       name:
         -  python-openstackclient
         -  openstack-selinux
       state: present

# Installation of MySQL and MariaDB Server
  -  name: Installation of MySQL and MariaDB Server in Compute (CentOS)
     yum:
       name:
         - mariadb
         - mariadb-server
         - python2-PyMySQL

  -  name: Configuration of MySQL and MariaDB Server in Compute (CentOS)
     template:
       src: roles/Compute_SQL/templates/openstack.cnf.j2
       dest: /etc/my.cnf.d/openstack.cnf

  -  name: Enable and Start MySQL and MariaDB in Compute (CentOS)
     systemd:
       name: mariadb.service
       state: restarted
       enabled: true

# Installation of Message Queue
  -  name: Installation of Message Queue (RabbitMQ-Server) in Compute (CentOS)
     yum:
       name: rabbitmq-server
       state: present

  -  name: Remove OpenStack as User for Message Queue in Compute (CentOS)
     command: "rabbitmqctl delete_user openstack"
     ignore_errors: yes
     changed_when: false

  -  name: Add OpenStack as User for Message Queue in Compute (CentOS)
     command: "rabbitmqctl add_user openstack RABBIT_PASS"
     ignore_errors: yes
     changed_when: false

  -  name: Modify Permissions for Openstack for Message Queue in Compute (CentOS)
     command: "rabbitmqctl set_permissions openstack '.*' '.*' '.*'"
     ignore_errors: yes
     changed_when: false

  -  name: Enable and Start Message Queue in Compute (CentOS)
     systemd:
       name: rabbitmq-server.service
       state: restarted
       enabled: true

# Installation of Memcached
  -  name: Installation of Memcached in Compute (CentOS)
     yum:
       name:
         - memcached
         - python-memcached

  -  name: Enable and Start Memcached in Compute (CentOS)
     systemd:
       name: memcached.service
       state: restarted
       enabled: true

# Installation of ETCD
  -  name: Installation of ETCD in Compute (CentOS)
     yum:
       name: etcd
       state: present

  -  name: Configuration of ETCD in Compute (CentOS)
     blockinfile:
       path:  /etc/etcd/etcd.conf
       block: |
         #[Member]
         ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
         ETCD_LISTEN_PEER_URLS="http://{{ ansible_default_ipv4.address }}:2380"
         ETCD_LISTEN_CLIENT_URLS="http://{{ ansible_default_ipv4.address }}:2379"
         ETCD_NAME="controller"
         #[Clustering]
         ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ ansible_default_ipv4.address }}:2380"
         ETCD_ADVERTISE_CLIENT_URLS="http://{{ ansible_default_ipv4.address }}:2379"
         ETCD_INITIAL_CLUSTER="controller=http://{{ ansible_default_ipv4.address }}:2380"
         ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
         ETCD_INITIAL_CLUSTER_STATE="new"

  -  name: Enable and Start ETCD in Compute (CentOS)
     systemd:
       name: etcd
       state: started
       enabled: true


