# NTP
  -  name: Install NTP 
     apt:
       name: chrony
       state: present

  -  name: Enable and Start NTP
     systemd:
       name: chrony
       state: restarted
       enabled: true

# OpenStack 
  -  name: Installation of OpenStack Client 
     apt:
       name: python3-openstackclient
       state: present

# SQL 
  -  name: Installation of MariaDB and MySQL 
     apt:
       name:
         -  mariadb-server
         -  python3-pymysql
       state: present

  -  name: Creation of Configuration of MySQL for MariaDB
     file:
       path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
       state: touch

  -  name: Configuration of MySQL for MariaDB 
     copy:
       dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
       content: |
         [mysqld]
         bind-address = 10.0.0.11
         default-storage-engine = innodb
         innodb_file_per_table = on
         max_connections = 4096
         collation-server = utf8_general_ci
         character-set-server = utf8

  -  name: Enable and Start MySQL and MariaDB
     systemd:
       name: "{{ item }}"
       state: restarted
       enabled: true
     loop:
       - mysql
       - mariadb


# Message Queue
  -  name: Installation of Message Queue (RabbitMQ-Server)
     apt:
       name: rabbitmq-server
       state: present

  -  name: Remove OpenStack as User for Message Queue 
     command: "rabbitmqctl delete_user openstack"
     ignore_errors: yes
     changed_when: false

  -  name: Add OpenStack as User for Message Queue 
     command: "rabbitmqctl add_user openstack RABBIT_PASS"
     ignore_errors: yes
     changed_when: false

  -  name: Modify Permissions for Openstack for Message Queue 
     command: "rabbitmqctl set_permissions openstack '.*' '.*' '.*'"
     ignore_errors: yes
     changed_when: false

# Memcached
  -  name: Installation of Memcached 
     apt:
       name:
         -  memcached
         -  python3-memcache
       state: present

  -  name: Creation of Configuration of Memcached 
     template:
       src: roles/Ubuntu/templates/memcached.conf.j2
       dest: /etc/memcached.conf
       mode: 0644

  -  name: Enable and Start Memcached 
     systemd:
       name: memcached
       state: restarted
       enabled: true

# ETCD
  -  name: Installation of ETCD 
     apt:
       name: etcd
       state: present

  -  name: Configuration of ETCD 
     template:
       src: roles/Ubuntu/templates/etcd.conf.j2
       dest: /etc/default/etcd

  -  name: Enable and Start ETCD 
     systemd:
       name: etcd
       state: restarted
       enabled: true




